In [7]:
import pandas as pd 
import numpy as np

In [1]:
! pip install gensim

In [8]:
import gensim
import os

In [9]:
from nltk import sent_tokenize
from gensim.utils import simple_preprocess

story = []

for filename in os.listdir('data'):

    f = open(os.path.join('data' , filename))
    corpus = f.read()
    raw_sent = sent_tokenize(corpus)
    for sent in raw_sent:
        story.append(simple_preprocess(sent))

In [10]:
len(story)


145020

In [15]:
model = gensim.models.Word2Vec(window = 10 , min_count = 2 , vector_size=100)


In [16]:
model.build_vocab(story)

In [18]:
model.train(story , total_examples=model.corpus_count , epochs=model.epochs)


(6569387, 8628190)

In [19]:
model.wv.most_similar('daenerys')

[('stormborn', 0.8027845025062561),
 ('targaryen', 0.7211744785308838),
 ('unburnt', 0.7190722823143005),
 ('queen', 0.717086136341095),
 ('princess', 0.7059257626533508),
 ('myrcella', 0.6839273571968079),
 ('dorne', 0.6776132583618164),
 ('elia', 0.6645169854164124),
 ('aegon', 0.6497495770454407),
 ('viserys', 0.6401059627532959)]

In [20]:
model.wv.doesnt_match(['jon' , 'rikon' , 'robb' , 'arya' , 'sansa' , 'bran'])

'jon'

In [21]:
model.wv['jon']

array([-0.21857733,  0.13207267,  0.7625161 , -1.4980456 ,  1.198976  ,
       -0.17363526,  0.18357986,  1.0840641 , -0.337086  , -0.47082967,
       -1.3436638 ,  0.04040238,  0.71111584, -2.2786539 ,  0.5486591 ,
       -0.21266502,  0.84898293,  3.687128  , -0.2938284 , -1.5475057 ,
        2.0647228 , -2.2768552 ,  0.07377105,  1.5824118 , -0.1052131 ,
       -0.8913369 ,  1.3136469 ,  0.7429693 ,  0.49577004, -0.46977618,
       -1.2742864 ,  0.0492071 , -0.10855082, -0.9648634 ,  0.12361725,
        0.7450999 ,  1.399237  ,  0.20614523,  1.7450407 , -1.7099447 ,
       -1.4637947 , -2.525824  ,  0.394485  ,  0.3531803 ,  1.8047923 ,
       -2.5321014 , -0.05919681,  0.9773565 , -2.660632  ,  1.4719738 ,
       -0.78539526, -0.7187462 ,  0.5078986 , -0.3848111 , -0.8303193 ,
        0.895676  , -0.6774761 , -2.0615163 ,  0.6055417 , -0.74015033,
        0.6055538 ,  2.5276246 ,  0.48242941, -1.7012683 ,  0.06158523,
       -0.62488395,  0.5966953 ,  2.0707471 , -0.4833258 , -0.72

In [22]:
model.wv['king']

array([ 0.80512935,  0.33053604,  1.6006033 ,  0.718603  , -1.9024364 ,
       -0.40286598,  0.96152836, -0.42633814, -1.4868512 ,  0.2963571 ,
       -1.1879234 ,  0.53272104, -0.06489602,  1.502804  , -3.757138  ,
       -0.47489873, -0.8382431 ,  3.7913496 , -0.38698068,  0.22515586,
        1.2721101 , -0.19896553,  1.7517723 , -2.7388935 , -2.4944596 ,
        2.0695987 , -1.2553504 , -2.1235259 ,  0.8312067 ,  0.20739086,
       -2.6177452 ,  1.5717885 ,  0.26655057, -0.33903632,  2.0363564 ,
       -3.39234   , -1.5587674 , -1.9908112 ,  1.9093196 , -2.4780545 ,
       -0.19565743,  2.40674   ,  2.5760584 , -0.6434966 , -0.328323  ,
       -2.054175  ,  0.837834  , -2.8774207 ,  3.913994  , -2.5680559 ,
       -3.6288407 , -1.0645684 , -0.76691204, -4.0046234 ,  2.9658334 ,
       -0.20019767,  1.2575809 ,  1.5993365 ,  1.2352884 ,  1.3290191 ,
        1.5433902 ,  1.2938014 ,  0.2599424 ,  1.3779962 ,  1.6270822 ,
        0.9764589 ,  0.13470198,  0.54221   ,  0.477321  , -1.47

In [23]:
model.wv.similarity('arya' , 'sansa')

0.85288346

In [24]:
model.wv.similarity('cersei' , 'sansa')

0.723963

In [27]:
model.wv.similarity('tywin' , 'sansa')

0.24334416

In [28]:
model.wv.get_normed_vectors()

array([[-0.03606518, -0.06995859,  0.1825786 , ..., -0.06166117,
         0.03473006,  0.147123  ],
       [-0.14958255, -0.19424374,  0.07923919, ..., -0.15320875,
        -0.04714683,  0.10915336],
       [ 0.1320291 , -0.1101193 , -0.09927493, ..., -0.03580953,
         0.11875191, -0.07408402],
       ...,
       [-0.01409586,  0.02770411, -0.05670645, ..., -0.1649089 ,
         0.10390353, -0.07959574],
       [-0.03949534,  0.03937107,  0.19262905, ..., -0.00893714,
         0.22912239, -0.11114555],
       [-0.07144967,  0.08688797,  0.08168438, ..., -0.03672306,
         0.1049761 , -0.07994991]], dtype=float32)

In [39]:
model.wv.get_normed_vectors().shape

(17453, 100)

In [29]:
# Dimension reduction from 100-D to 3-D using PCA

from sklearn.decomposition import PCA
pca = PCA(n_components=3)

In [30]:
X = pca.fit_transform(model.wv.get_normed_vectors())

In [33]:
X[:5]

array([[ 0.16776165,  0.59841615, -0.04129601],
       [ 0.14903298,  0.34618837,  0.05365224],
       [-0.27928472,  0.5795268 ,  0.26151034],
       [ 0.02671852,  0.37727186, -0.10233653],
       [-0.09501389,  0.52285224,  0.31028628]], dtype=float32)

In [34]:
X.shape

(17453, 3)

In [41]:
! pip install plotly

   ---------------------------------------- 0.0/19.1 MB ? eta -:--:--
   ---------------------------------------- 0.0/19.1 MB ? eta -:--:--
    --------------------------------------- 0.3/19.1 MB ? eta -:--:--
   - -------------------------------------- 0.5/19.1 MB 1.2 MB/s eta 0:00:16
   - -------------------------------------- 0.8/19.1 MB 1.3 MB/s eta 0:00:15
   -- ------------------------------------- 1.0/19.1 MB 1.3 MB/s eta 0:00:14
   -- ------------------------------------- 1.3/19.1 MB 1.3 MB/s eta 0:00:14
   --- ------------------------------------ 1.8/19.1 MB 1.4 MB/s eta 0:00:13
   ---- ----------------------------------- 2.1/19.1 MB 1.5 MB/s eta 0:00:12
   ----- ---------------------------------- 2.6/19.1 MB 1.6 MB/s eta 0:00:11
   ------- -------------------------------- 3.4/19.1 MB 1.8 MB/s eta 0:00:09
   -------- ------------------------------- 4.2/19.1 MB 2.0 MB/s eta 0:00:08
   --------- ------------------------------ 4.7/19.1 MB 2.1 MB/s eta 0:00:07
   ------------ ----

In [43]:
import plotly.express as px
fig = px.scatter_3d(X[:100] , x = 0  , y = 1 , z = 2 , color=y[:100])
fig.show()

In [5]:
# Implemenatation of CBOW

import tensorflow as tf
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense , Embedding , Lambda
from tensorflow.keras.preprocessing.text import Tokenizer
from tensorflow.keras.utils import to_categorical
import numpy as np
import matplotlib.pyplot as plt
from sklearn.decomposition import PCA

# define the corpus
corpus = ['The cat sat on the mat',
    'The dog ran in the park',
    'The bird sang in the tree'
    ]

# Convert the corpus to a sequence of integers 
tokenizer = Tokenizer()
tokenizer.fit_on_texts(corpus)
sequences = tokenizer.texts_to_sequences(corpus)
print(sequences)

[[1, 3, 4, 5, 1, 6], [1, 7, 8, 2, 1, 9], [1, 10, 11, 2, 1, 12]]


Now , window size = 2

In [ ]:
# Defining the parameters 
vocab_size = len(tokenizer.word_index) + 1
embedding_size = 10
window_size = 2

# Generate the context-target pairs
contexts = []
targets = []

for sequence in sequences:
    

